apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-echo48118aa2-ee5e-4549-be78-27dd947f0121.fullname" . }}-config
  labels:
    {{- include "go-echo48118aa2-ee5e-4549-be78-27dd947f0121.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value }}
{{- end }}
