apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-echo47e427be-b05c-4fd9-b6fa-a790a52614ed.fullname" . }}-config
  labels:
    {{- include "go-echo47e427be-b05c-4fd9-b6fa-a790a52614ed.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value }}
{{- end }}
