apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-echo25ad89ac-24d4-4c78-86d9-9dc092a60937.fullname" . }}-config
  labels:
    {{- include "go-echo25ad89ac-24d4-4c78-86d9-9dc092a60937.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value }}
{{- end }}
