apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echo39f6f48e-4d33-456c-92ab-046b41e266c9.fullname" . }}
  labels:
    {{- include "go-echo39f6f48e-4d33-456c-92ab-046b41e266c9.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echo39f6f48e-4d33-456c-92ab-046b41e266c9.selectorLabels" . | nindent 6 }}
