apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-echoac4c3662-edd5-4344-bdc5-de900dbe1c95.fullname" . }}
  labels:
    {{- include "go-echoac4c3662-edd5-4344-bdc5-de900dbe1c95.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: svchttp
  selector:
    {{- include "go-echoac4c3662-edd5-4344-bdc5-de900dbe1c95.selectorLabels" . | nindent 6 }}
